baseURL: "https://cssz.ch/"
title: "Czech and Slovak Students in Zurich"
languageCode: 'en-us'
permalinks:
  post: /:year/:month/:title/
theme:
- cssz
- hugo-theme-stack

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-5CRSPLB515

minify:
  disableXML: true
  minifyOutput: true

menu:
  main: []
#    - identifier: categories
#      name: categories
#      url: /categories/
#      weight: 10
#    - identifier: tags
#      name: tags
#      url: /tags/
#      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

markup:
  goldmark:
    renderer:
      unsafe: true
