languageCode: en-us
title: Example Site

params:
  mainSections:
    - posts
    - events
  #featuredImageField: image
  rssFullContent: true
  favicon: /images/icon/favicon.ico

  dateFormat:
    published: 2 Jan 2006
    lastUpdated: "2 Jan 2006, 15:04 MST"
    event: "2 Jan 2006, 15:04"
    eventEndShort: "15:04"

  sidebar:
    compact: false
    #emoji: 🍥
    subtitle:
    avatar:
      enabled: true
      local: true
      src: images/TEST_13_crop2.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false
    #...

  widgets:
    homepage:
      - type: search
#      - type: archives
#        params:
#          limit: 5
#      - type: categories
#        params:
#          limit: 10
#      - type: tag-cloud
#        params:
#          limit: 10
    page:
      - type: toc

  opengraph:
    #twitter:
      # Your Twitter username
      #site:

      # Available values: summary, summary_large_image
      #card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: false

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  #main: []

#  social:
#    - identifier: github
#      name: GitHub
#      url: https://github.com/CaiJimmy/hugo-theme-stack
#      params:
#        icon: brand-github
#
#    - identifier: twitter
#      name: Twitter
#      url: https://twitter.com
#      params:
#        icon: brand-twitter
